import AppKit
import Foundation
import Testing
@testable import Northy

@MainActor
/// Логика истории буфера без NSPasteboard (его не замокаешь): чистые функции
/// и стор на временном каталоге — реальные данные приложения не трогаются.
struct ClipboardStoreTests {

    private func textEntry(_ text: String) -> ClipboardStore.Entry {
        ClipboardStore.Entry(content: .text(text))
    }

    private func tempDirectory() -> URL {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("NorthyTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    // MARK: merged — вставка, дедупликация, лимит

    @Test func mergedInsertsNewEntryOnTop() {
        let result = ClipboardStore.merged(
            history: [textEntry("a")],
            appending: textEntry("b"),
            limit: 100
        )
        #expect(result.map(\.id).count == 2)
        #expect(entryText(result[0]) == "b")
        #expect(entryText(result[1]) == "a")
    }

    @Test func mergedBumpsDuplicateInsteadOfSecondRow() {
        let old = textEntry("same")
        let result = ClipboardStore.merged(
            history: [old, textEntry("a")],
            appending: textEntry("same"),
            limit: 100
        )
        #expect(result.count == 2)
        #expect(entryText(result[0]) == "same")
        #expect(result[0].id != old.id, "наверх поднимается новая запись")
        #expect(!result.contains(where: { $0.id == old.id }), "старая исчезает")
    }

    @Test func mergedTrimsOverflowFromTail() {
        let base = (0..<10).map { textEntry("t\($0)") }
        let result = ClipboardStore.merged(
            history: base,
            appending: textEntry("new"),
            limit: 10
        )
        #expect(result.count == 10)
        #expect(entryText(result[0]) == "new")
        #expect(!result.contains(where: { entryText($0) == "t0" }), "выпадает самый старый")
    }

    @Test func mergedDoesNotDedupAcrossKinds() {
        let result = ClipboardStore.merged(
            history: [ClipboardStore.Entry(content: .files([URL(fileURLWithPath: "/tmp/a")]))],
            appending: ClipboardStore.Entry(content: .text("/tmp/a")),
            limit: 100
        )
        #expect(result.count == 2, "текст и файл с одинаковым содержимым — разные записи")
    }

    private func entryText(_ entry: ClipboardStore.Entry) -> String {
        guard case .text(let text) = entry.content else { return "" }
        return text
    }

    // MARK: truncated — лимит ~1 МБ

    @Test func truncatedKeepsSmallTextIntact() {
        #expect(ClipboardStore.truncated("привет") == "привет")
    }

    @Test func truncatedCutsMegabyteText() {
        let big = String(repeating: "а", count: ClipboardStore.textByteLimit + 10)
        let result = ClipboardStore.truncated(big)
        #expect(result.utf8.count <= ClipboardStore.textByteLimit + 64)
        #expect(result.hasSuffix("[усечено до 1 МБ]"))
        #expect(result.filter { $0 == "\u{FFFD}" }.count <= 1)
    }

    // MARK: preview — короткая строка для списка

    @Test func previewCollapsesWhitespaceAndCapsLength() {
        #expect(ClipboardStore.preview(of: "  a\n\n b\t c  ") == "a b c")
        let long = String(repeating: "x", count: 5_000)
        #expect(ClipboardStore.preview(of: long).count <= ClipboardStore.previewLimit)
    }

    // MARK: пароли и служебные записи

    @Test func ignoresConcealedTransientAndAutoGenerated() {
        for raw in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            #expect(ClipboardStore.shouldIgnore(types: [.string, NSPasteboard.PasteboardType(raw)]), "\(raw)")
        }
        #expect(!ClipboardStore.shouldIgnore(types: [.string]))
        #expect(!ClipboardStore.shouldIgnore(types: nil))
    }

    // MARK: картинки — оригинал на диске, а не миниатюра в JSON

    @Test func storedImageKeepsOriginalResolution() throws {
        let dir = tempDirectory()
        let ref = try #require(ClipboardImages.store(Self.pngData(width: 2000, height: 1000), in: dir))
        #expect(ref.pixelWidth == 2000)
        #expect(ref.pixelHeight == 1000)
        let saved = try #require(NSBitmapImageRep(data: Data(contentsOf: dir.appendingPathComponent(ref.filename))))
        #expect(saved.pixelsWide == 2000, "в буфер возвращается оригинал, не 512px")
    }

    @Test func storingSameImageTwiceGivesSameFile() throws {
        let dir = tempDirectory()
        let data = Self.pngData(width: 30, height: 20)
        let a = try #require(ClipboardImages.store(data, in: dir))
        let b = try #require(ClipboardImages.store(data, in: dir))
        #expect(a.filename == b.filename)
        let files = try FileManager.default.contentsOfDirectory(atPath: dir.path)
        #expect(files.count == 1)
    }

    @Test func storeRejectsGarbage() {
        #expect(ClipboardImages.store(Data([0, 1, 2]), in: tempDirectory()) == nil)
    }

    @Test func thumbnailFitsMaxPixel() throws {
        let dir = tempDirectory()
        let ref = try #require(ClipboardImages.store(Self.pngData(width: 800, height: 400), in: dir))
        let thumb = try #require(ClipboardImages.thumbnail(at: dir.appendingPathComponent(ref.filename), maxPixel: 100))
        #expect(max(thumb.width, thumb.height) <= 100)
    }

    // MARK: стор на временном каталоге

    @Test func removingImageEntryDeletesItsFile() throws {
        let dir = tempDirectory()
        let store = ClipboardStore(directory: dir)
        store.load()
        let ref = try #require(ClipboardImages.store(Self.pngData(width: 10, height: 10), in: store.imagesDirectory))
        store.add(.image(ref))
        let file = store.imageURL(for: ref)
        #expect(FileManager.default.fileExists(atPath: file.path))

        store.remove(store.history[0])
        #expect(!FileManager.default.fileExists(atPath: file.path))
    }

    @Test func evictedAndClearedImagesAreDeleted() throws {
        let dir = tempDirectory()
        let store = ClipboardStore(directory: dir, limit: 2)
        store.load()
        let first = try #require(ClipboardImages.store(Self.pngData(width: 11, height: 11), in: store.imagesDirectory))
        store.add(.image(first))
        store.add(.text("a"))
        store.add(.text("b"))
        #expect(!FileManager.default.fileExists(atPath: store.imageURL(for: first).path), "вытесненная лимитом")

        let second = try #require(ClipboardImages.store(Self.pngData(width: 12, height: 12), in: store.imagesDirectory))
        store.add(.image(second))
        store.clear()
        #expect(!FileManager.default.fileExists(atPath: store.imageURL(for: second).path))
    }

    @Test func loadPrunesOrphanImageFiles() throws {
        let dir = tempDirectory()
        let store = ClipboardStore(directory: dir)
        store.load()
        let kept = try #require(ClipboardImages.store(Self.pngData(width: 13, height: 13), in: store.imagesDirectory))
        store.add(.image(kept))
        store.flush()
        let orphan = store.imagesDirectory.appendingPathComponent("orphan.png")
        try Data([1]).write(to: orphan)

        let reloaded = ClipboardStore(directory: dir)
        reloaded.load()
        #expect(!FileManager.default.fileExists(atPath: orphan.path))
        #expect(FileManager.default.fileExists(atPath: reloaded.imageURL(for: kept).path))
    }

    @Test func historySurvivesReloadWithDates() {
        let dir = tempDirectory()
        let store = ClipboardStore(directory: dir)
        store.load()
        store.add(.text("hello"))
        store.flush()

        let reloaded = ClipboardStore(directory: dir)
        reloaded.load()
        #expect(reloaded.history.count == 1)
        #expect(reloaded.history.first?.date != nil)
    }

    // MARK: закреплённые записи

    private func pinnedEntry(_ text: String) -> ClipboardStore.Entry {
        var entry = textEntry(text)
        entry.isPinned = true
        return entry
    }

    @Test func pinnedEntriesAreNeverEvicted() {
        // Хронологический лог: старые в начале.
        let history = [pinnedEntry("p1"), textEntry("a"), pinnedEntry("p2"), textEntry("b"), textEntry("c")]
        let result = ClipboardStore.merged(history: history, appending: textEntry("d"), limit: 3)
        #expect(Set(result.map(entryText)) == ["p1", "p2", "b", "c", "d"], "лимит считает только незакреплённые")
        #expect(result.first.map(entryText) == "d")
    }

    @Test func copyingPinnedTextAgainKeepsPin() {
        let result = ClipboardStore.merged(history: [pinnedEntry("важное"), textEntry("a")], appending: textEntry("важное"), limit: 10)
        #expect(result.count == 2)
        #expect(result[0].isPinned, "повтор закреплённого поднимается наверх и остаётся закреплённым")
    }

    @Test func clearKeepsPinnedAndPinSurvivesReload() {
        let dir = tempDirectory()
        let store = ClipboardStore(directory: dir)
        store.load()
        store.add(.text("обычная"))
        store.add(.text("закреплённая"))
        store.togglePin(store.history[0])
        store.clear()
        #expect(store.history.map(entryText) == ["закреплённая"])
        store.flush()

        let reloaded = ClipboardStore(directory: dir)
        reloaded.load()
        #expect(reloaded.history.first?.isPinned == true)
    }

    @Test func limitChangeTrimsOnlyUnpinned() {
        let dir = tempDirectory()
        let store = ClipboardStore(directory: dir, limit: 10)
        store.load()
        for index in 0..<5 { store.add(.text("t\(index)")) }
        store.togglePin(store.history[4])   // самая старая «t0»
        store.limit = 2
        #expect(store.history.map(entryText) == ["t4", "t3", "t0"])
    }

    // MARK: поиск и фильтр

    @Test func filterByQueryAndKind() {
        let entries = [
            textEntry("Ошибка сборки: missing symbol"),
            ClipboardStore.Entry(content: .files([URL(fileURLWithPath: "/tmp/Отчёт.pdf")])),
            ClipboardStore.Entry(content: .image(ImageRef(filename: "x.png", pixelWidth: 1, pixelHeight: 1))),
            textEntry("git push"),
        ]
        #expect(ClipboardStore.filtered(entries, query: "", kind: .all).count == 4)
        #expect(ClipboardStore.filtered(entries, query: "ОШИБКА", kind: .all).map(entryText) == ["Ошибка сборки: missing symbol"])
        #expect(ClipboardStore.filtered(entries, query: "отчёт", kind: .all).count == 1, "ищет и по именам файлов")
        #expect(ClipboardStore.filtered(entries, query: "", kind: .text).count == 2)
        #expect(ClipboardStore.filtered(entries, query: "", kind: .files).count == 1)
        #expect(ClipboardStore.filtered(entries, query: "", kind: .images).count == 1)
        #expect(ClipboardStore.filtered(entries, query: "push", kind: .files).isEmpty)
    }

    /// Формат clipboard.json прошлых версий: синтезированный Codable, картинка
    /// лежит base64 прямо в JSON, даты нет. История не должна пропасть.
    @Test func legacyHistoryIsMigrated() throws {
        let dir = tempDirectory()
        let png = Self.pngData(width: 40, height: 30).base64EncodedString()
        let legacy = """
        [
          {"content":{"text":{"_0":"старый текст"}},"id":"290E063B-2B44-4736-B0C2-21882A7D31FA"},
          {"content":{"files":{"_0":["file:///tmp/a.txt"]}},"id":"390E063B-2B44-4736-B0C2-21882A7D31FA"},
          {"content":{"image":{"_0":"\(png)"}},"id":"490E063B-2B44-4736-B0C2-21882A7D31FA"}
        ]
        """
        try Data(legacy.utf8).write(to: dir.appendingPathComponent("clipboard.json"))

        let store = ClipboardStore(directory: dir)
        store.load()
        #expect(store.history.count == 3)
        #expect(store.history.allSatisfy { !$0.isPinned }, "в старом формате закреплений не было")
        #expect(entryText(store.history[0]) == "старый текст")
        guard case .files(let urls) = store.history[1].content else {
            Issue.record("files не распознаны"); return
        }
        #expect(urls.map(\.path) == ["/tmp/a.txt"])
        guard case .image(let ref) = store.history[2].content else {
            Issue.record("image не распознана"); return
        }
        #expect(ref.pixelWidth == 40)
        #expect(FileManager.default.fileExists(atPath: store.imageURL(for: ref).path))

        store.flush()
        let json = try String(contentsOf: dir.appendingPathComponent("clipboard.json"), encoding: .utf8)
        #expect(!json.contains(png), "base64 картинки больше не лежит в JSON")
    }

    /// PNG-заглушка заданного размера, без файлов на диске.
    static func pngData(width: Int, height: Int) -> Data {
        let rep = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: width,
            pixelsHigh: height,
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        )!
        return rep.representation(using: .png, properties: [:])!
    }
}
